#!/usr/bin/env zsh

# This script is meant to be called from nano with a special key binding in
# .nanorc. It allows the user to dispatch a key combo for "run" and see results
# immediately as though working in an IDE. Configured correctly, it saves a
# *ton* of time that would otherwise be spent switching between nano and the
# command line to test a script.

# So let's talk about configuration. For this to run, your .nanorc needs to have
# a key combo that executes the following pattern:
#	^T "nExecute" Enter
# The ^T summons the Execute prompt, the "nExecute" queues this script into the
# prompt, and the Enter runs it. You'll use the "bind" command in .nanorc, and
# you can use M-V to enter verbatim keystrokes to get ^T and Enter.

# And, of course, this script--or a symlink to it--needs to be in your path.

# Happy executing!

# Check for driver script in working directory and run if found
drv=".nExecute"
[[ -f $drv ]] && {
	eval "./$drv"
	exit 0
} || {
	echo "No .nExecute file found"
	exit 1
}
