disabled_rules:
    - identifier_name
    - function_body_length
    - type_body_length
opt_in_rules:
    - array_init
    - attributes
    - balanced_xctest_lifecycle
    - capture_variable
    - closure_body_length
    - collection_alignment
    - conditional_returns_on_newline
    - contains_over_filter_count
    - contains_over_filter_is_empty
    - contains_over_first_not_nil
    - contains_over_range_nil_comparison
    - convenience_type
    - discarded_notification_center_observer
    - discouraged_assert
    - discouraged_object_literal
    - discouraged_optional_boolean
    - discouraged_optional_collection
    - empty_collection_literal
    - empty_count
    - empty_string
    - empty_xctest_method
    - enum_case_associated_values_count
    - expiring_todo
    - explicit_acl
    - explicit_enum_raw_value
    - explicit_top_level_acl
    - explicit_type_interface
    - extension_access_modifier
    - fallthrough
    - fatal_error_message
    - file_header
    - file_name
    - file_name_no_space
    - file_types_order
    - first_where
    - flatmap_over_map_reduce
    - force_unwrapping
    - function_default_parameter_at_end
    - ibinspectable_in_extension
    - identical_operands
    - implicitly_unwrapped_optional
    - indentation_width
    - last_where
