#!/usr/bin/env bash

set -e

# Ensure interactive shell
[ -t 0 ] || {
    echo "$(basename "$0") requires an interactive shell" >&2
    exit 1
}

# Ensure macOS
[ "$(uname -s)" = "Darwin" ] || {
    echo "$(basename "$0") is only available on macOS" >&2
    exit 1
}

# Ensure root privileges
[ $EUID = 0 ] || {
    echo "$(basename "$0") requires root privileges" >&2
    exit 1
}

# Define confirmation function
confirm() {
    until false; do
        read -r -p "$1 (y/n) " answer
        printf '\033[0F\033[0K'
        [ "$answer" = y ] && return 0
        [ "$answer" = n ] && return 1
    done
}

# Clear caches
confirm "Clear caches?" && {
    d_caches="$HOME/Library/Caches"
    rm -rf "${d_caches:?}/*" "${d_caches:?}/.*"
    echo "Cleared caches: $d_caches" >&2
}

# Clear system logs
confirm "Clear system logs?" && {
    d_system_logs="/var/log"
    rm -rf "${d_system_logs:?}/*" "${d_system_logs:?}/.*"
    echo "Cleared system logs: $d_system_logs" >&2
}

# Clear iMessage attachments
confirm "Clear local iMessage attachments and cache? (Will close the Messages app)" && {
    osascript -e 'tell application "Messages" to quit'
    rm -rf "$HOME/Library/Messages/Attachments"
    rm -rf "$HOME/Library/Messages/Caches"
    echo "Cleared local iMessage attachments and cache" >&2
}

# Prune Docker images
if [ -S "$HOME/.docker/run/docker.sock" ]; then
    confirm "Prune Docker?" && {
        docker system prune -af
        docker volume prune -af
        echo "Pruned docker system" >&2
    }
else
    echo "Docker daemon is not running; can't offer to prune Docker" >&2
fi

# Clean up homebrew
[ -n "${SUDO_USER+x}" ] && command -v brew >/dev/null && confirm "Clean up homebrew?" && {
    if sudo -u "$SUDO_USER" brew autoremove; then
        echo "Ran brew autoremove" >&2
    else
        :
    fi
    if sudo -u "$SUDO_USER" brew cleanup --prune all; then
        echo "Ran brew cleanup" >&2
    else
        :
    fi
}

# Remove Cargo build artifacts
dir_repos="$HOME/Repos"
[ -d "$dir_repos" ] && confirm "Remove Cargo build artifacts from $dir_repos?" && {
    while read -r c_toml; do
        d_repo="$(dirname "$c_toml")"
        d_target="$d_repo/target"
        [ -d "$d_target" ] && {
            git ls-files --error-unmatch "$d_target"
            case $? in
            0) # ./target file is tracked by git
                echo "Skipping $d_target; directory is tracked by git" >&2
                ;;
            1) # ./target file is not tracked by git
                [ -d "$d_target" ] && rm -rf "$d_target"
                echo "Removed $d_target" >&2
                ;;
            *) # git error (most likely this isn't a git repo, in which case we don't want to touch anything)
                echo "Skipping $d_target; unable to determine git status" >&2
                ;;
            esac
        }
    done < <(find "$dir_repos" -type f -name Cargo.toml -mindepth 2 -maxdepth 2)
}

# Exit
exit 0
