#!/usr/bin/env bash

set -e

# Ensure interactive shell
[ -t 0 ] || {
    echo "$(basename "$0") requires an interactive shell" >&2
    exit 1
}

# Ensure macOS
[ "$(uname -s)" = "Darwin" ] || {
    echo "$(basename "$0") is only available on macOS" >&2
    exit 1
}

# Ensure root privileges
[ $EUID = 0 ] || {
    echo "$(basename "$0") requires root privileges" >&2
    exit 1
}

# Define offer function
offer() {
    until false; do
        read -r -p "$1 (y/n) " answer
        printf '\033[0F\033[0K'
        [ "$answer" = y ] && return 0
        [ "$answer" = n ] && return 1
    done
}

# Define reporting function
report() {
    clr=35
    [ -n "${2+x}" ] && {
        [ "$2" = 0 ] || clr=31
    }
    echo -e "\033[$clr;1m$1\033[0m" >&2
}

# Clear caches
offer "Clear caches?" && {
    d_caches="$HOME/Library/Caches"
    rm -rf "${d_caches:?}/*" "${d_caches:?}/.*"
    report "Cleared caches: $d_caches"
}

# Clear system logs
offer "Clear system logs?" && {
    d_system_logs="/var/log"
    rm -rf "${d_system_logs:?}/*" "${d_system_logs:?}/.*"
    report "Cleared system logs: $d_system_logs"
}

# Clear iMessage attachments
offer "Clear local iMessage attachments and cache? (Will close the Messages app)" && {
    osascript -e 'tell application "Messages" to quit'
    rm -rf "$HOME/Library/Messages/Attachments"
    rm -rf "$HOME/Library/Messages/Caches"
    report "Cleared local iMessage attachments and cache"
}

# Prune Docker images
if [ -S "$HOME/.docker/run/docker.sock" ]; then
    offer "Prune Docker?" && {
        docker system prune -af
        docker volume prune -af
        report "Pruned docker system"
    }
else
    report "Docker daemon is not running; can't offer to prune Docker" 1
fi

# Clean up homebrew
[ -n "${SUDO_USER+x}" ] && command -v brew >/dev/null && offer "Clean up homebrew?" && {
    if sudo -u "$SUDO_USER" brew autoremove; then
        report "Ran brew autoremove"
    else
        :
    fi
    if sudo -u "$SUDO_USER" brew cleanup --prune all; then
        report "Ran brew cleanup"
    else
        :
    fi
}

# Remove Cargo build artifacts
dir_repos="$HOME/Repos"
[ -d "$dir_repos" ] && offer "Remove Cargo build artifacts from $dir_repos?" && {
    while read -r c_toml; do
        d_repo="$(dirname "$c_toml")"
        d_target="$d_repo/target"
        [ -d "$d_target" ] && {
            git ls-files --error-unmatch "$d_target"
            case $? in
            0) # ./target file is tracked by git
                report "Skipping $d_target; directory is tracked by git" 1
                ;;
            1) # ./target file is not tracked by git
                [ -d "$d_target" ] && rm -rf "$d_target"
                report "Removed $d_target"
                ;;
            *) # git error (most likely this isn't a git repo, in which case we don't want to touch anything)
                report "Skipping $d_target; unable to determine git status" 1
                ;;
            esac
        }
    done < <(find "$dir_repos" -type f -name Cargo.toml -mindepth 2 -maxdepth 2)
    report "Removed Cargo build artifacts from $dir_repos"
}

# Restart Shortcuts Events
offer "Kill (restart) Shortcuts events?" && {
    killall "siriactionsd" 2>/dev/null || :
    report "Killed (restarted) Shortcuts events"
}

# Exit
exit 0
