#!/usr/bin/env bash

# Set predicate
pred='select(.kind != "style")' # We want swift-format to do most of the actual formatting

# Open final string
final="only_rules:"

# Open loop through specifified rules
while read -r rule
do

	# Append rule to final
	final="$final\n  - $rule"

done < <(
	swiftlintToJson | \
		jq '.[] | select(.analyzer == false)' | jq "$pred" | jq -r '.id'
)

echo -e "$final"
