#!/usr/bin/env bash

# shellcheck disable=SC2015

# Make sure swift-format is installed
which swift-format &> /dev/null || {
	echo "Please install swift-format" >&2
	exit 1
}

# Make sure jq is installed
which jq &> /dev/null || {
	echo "Please install jq" >&2
	exit 1
}

# Assign argument
f=$1

# Make sure file is named .swift-format (rigid, but safe)
wants=".swift-format"
[ "$(basename "$f" 2> /dev/null )" = $wants ] 2> /dev/null || {
	echo "Please supply a file called $wants." >&2
	exit 1
}

# Make sure file exists
[ -f "$f" ] || {
	echo "$f does not exist." >&2
	exit 1
}

# Get default configuration
configDefault=$(swift-format dump-configuration)

# Get all default paths
paths=$(
	echo "$configDefault" | \
		jq -c 'paths(type != "array" and type != "object")' | \
		sort
)

# Set status
didFindIssues=0

# Open variable
final=""

# Loop through paths
while read -r singlePath
do

	# Report paths that don't have values in the config file
	val=$(jq -M "getpath($singlePath)" "$f")
	[ "$val" = null ] && {
		final="$(
			printf "%s\n\033[31mMISSING\033[0m %-60s \033[32mDEFAULT\033[0m %s" \
			"$final" \
			"$singlePath" \
			"$(echo "$configDefault" | jq -M "getpath($singlePath)")"
		)"
		didFindIssues=1
	}

# Close loop
done < <(echo "$paths")

# Exit
[ "$didFindIssues" = 1 ] && {
	final=$(echo "$final" | perl -pe 's/^\n//g')
	echo -e "$final" >&2
	exit 1
} || {
	exit 0
}
