#!/usr/bin/env bash

# Set custom predicate
pred='select(.kind != "style") | select(.id | IN("explicit_type_interface", "explicit_acl", "explicit_top_level_acl") | not)'

# Add comments
comments=("We want swift-format to handle style fixes" "The access level and type rules are just annoying")

# Set predicate to exclude analyzer rules
predNoAnalyzer='select(.analyzer | not)'

# Set header comment
header="# Generated using:\n#   swiftlint $(swiftlint --version)\n# Predicates:\n#   $predNoAnalyzer\n#   $pred"

# Add comments to header
didPlaceCommentsHeader=0
for comment in "${comments[@]}"; do
    [ "$didPlaceCommentsHeader" = 0 ] && {
        header="$header\n# Comments:"
        didPlaceCommentsHeader=1
    }
    header="$header\n#   $comment"
done

# Open final string
final="$header\n\nonly_rules:"

# Open loop through specifified rules
while read -r rule; do

    # Append rule to final
    final="$final\n  - $rule"

done < <(
    swiftlintToJson |
        jq '.[]' | jq "$predNoAnalyzer" | jq "$pred" | jq -r '.id'
)

echo -e "$final"
