#!/usr/bin/env bash

# shellcheck disable=SC2015

# Keeps your .swift-format up to date by making sure you've explicitly assigned
# all values found in `swift-format dump-configuration` and detecting values
# that aren't found in the default.

# Make sure swift-format is installed
which swift-format &> /dev/null || {
	echo "Please install swift-format" >&2
	exit 1
}

# Make sure jq is installed
which jq &> /dev/null || {
	echo "Please install jq" >&2
	exit 1
}

# Assign argument
f=$1

# Make sure file is named .swift-format (rigid, but safe)
wants=".swift-format"
[ "$(basename "$f" 2> /dev/null )" = $wants ] 2> /dev/null || {
	echo "Please supply a file called $wants." >&2
	exit 1
}

# Make sure file exists
[ -f "$f" ] || {
	echo "$f does not exist." >&2
	exit 1
}

# Get default configuration
configDefault=$(swift-format dump-configuration)

# Set status
didFindIssues=0

# Open variable
final=""

# Loop through paths in default configuration
while read -r singlePath
do

	# Report paths that don't have values in the config file
	val=$(jq -M "getpath($singlePath)" "$f")
	[ "$val" = null ] && {
		final="$(
			printf "%s\n\033[31mNOT IN CONFIG  \033[0m%-60s\033[32mDEFAULT\033[0m %s" \
			"$final" \
			"$singlePath" \
			"$(echo "$configDefault" | jq -M "getpath($singlePath)")"
		)"
		didFindIssues=1
	}

# Close loop
done < <(
	echo "$configDefault" | \
		jq -c 'paths(type != "array" and type != "object")' | \
		sort
)

# Loop through paths in config file
while read -r singlePath
do

	# Report paths aren't valid (i.e. don't appear in the default config)
	val=$(echo "$configDefault" | jq -M "getpath($singlePath)")
	[ "$val" = null ] && {
		final="$(
			printf "%s\n\033[33mNOT IN DEFAULT\033[0m %s" \
			"$final" \
			"$singlePath"
		)"
		didFindIssues=1
	}

# Close loop
done < <(
	jq -c 'paths(type != "array" and type != "object")' "$f" | sort
)

# Exit
[ "$didFindIssues" = 1 ] && {
	final=$(echo "$final" | perl -pe 's/^\n//g')
	echo -e "$final" >&2
	exit 1
} || {
	exit 0
}
